# Tên của workflow
name: Java CI with Maven

# Kích hoạt workflow khi có push hoặc pull request
# vào nhánh 'main' (hoặc 'master' tùy bạn đặt)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Các công việc (jobs) sẽ chạy
jobs:
  build:
    # Chạy trên máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Step 1: Lấy code từ repository về
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Cài đặt Java (JDK 17)
      # (Bạn có thể đổi '17' thành '11' hoặc '21' tùy dự án)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build và Test với Maven
      # Lệnh 'mvn clean install' sẽ tự động chạy test
      - name: Build and test with Maven
        run: mvn clean install
